sonar.projectKey=TEPIS
sonar.projectName=TEPIS
sonar.projectVersion=1.0
sonar.sources=.
sonar.language=py
sonar.sourceEncoding=UTF-8
sonar.python.version=3.8
sonar.host.url=http://localhost:9000
sonar.token=sqp_3bbdbdb08a1d33ce67419afd458e1bc52b1fa952
